name: Build and deploy Node.js app to Azure Web App - todoappp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      
      - name: Compress build folder
        shell: pwsh
        run: |
          $excludePaths = @('node_modules\', '.git\')
          $sourcePath = '.'
          $zipFilePath = 'build.zip'
          $zipFilePath | Remove-Item -ErrorAction Ignore
          Add-Type -AssemblyName 'System.IO.Compression.FileSystem'
          [System.IO.Compression.ZipFile]::CreateFromDirectory($sourcePath, $zipFilePath, [System.IO.Compression.CompressionLevel]::Optimal, $false)
          $zip = [System.IO.Compression.ZipFile]::Open($zipFilePath, [System.IO.Compression.ZipArchiveMode]::Update)
          foreach ($excludePath in $excludePaths) {
            $files = Get-ChildItem -Path $sourcePath -Recurse -Exclude $excludePath
            foreach ($file in $files) {
              $entryName = $file.FullName.Substring($sourcePath.Length + 1)
              $entry = $zip.GetEntry($entryName)
              if ($entry) {
                $entry.Delete()
              }
            }
          }
          $zip.Dispose()

      - name: Upload compressed artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Decompress artifact
        run: unzip build.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2A80937E1B5D4E70B9FA697AE355E037 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F3047086A1EB41A89A4220BEABDDA8E8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_44AF3210F971497CB5BE2973328465BB }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'todoappp'
          slot-name: 'Production'
          package: .
