name: Build and deploy Node.js app to Azure Web App - emp-todo-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      
      - name: Compress build folder
        run: |
          tar -czf build.tar.gz . --exclude=**/node_modules/** --exclude=**/.git/**

      - name: Upload compressed artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Decompress artifact
        run: tar -xzf build.tar.gz

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0D24A85F27D346CEBDF79CE620153E13 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5AE0F0B9459B4558AB75E0BDDBAAA2B2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C26AC133C5C34B5D818B9F42B61B2727 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'emp-todo-app'
          slot-name: 'Production'
          package: .
